app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(UserMixin,db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer,primary_key = True)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))
    username = db.Column(db.String(255))
    email = db.Column(db.String(255),unique = True,index = True)
    bio = db.Column(db.String)
    posts = db.relationship("Post", backref = "user", lazy = "dynamic")
    pass_secure = db.Column(db.String(255))

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)


    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)

    def __repr__(self):
        return f'User {self.username}'

class Post(db.Model):
    __tablename__ = "posts"
    id  = db.Column(db.Integer,primary_key = True)
    title = db.Column(db.String)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))
    content = db.Column(db.String)
    time = db.Column(db.String)
    image = db.Column(db.String)
    # comments = db.relationship("Comment",backref = "post", lazy = "dynamic")
    # def get_post_comments(self):
    #     return Comment.query.filter_by(post_id = self.id)

    def save_post(self):
        db.session.add(self)
        db.session.commit()

class Comment(db.Model):
    __tablename__ = "comments"
    id = db.Column(db.Integer, primary_key = True)
    name = db.Column(db.String)
    title = db.Column(db.String)
    content = db.Column(db.String)
    post_id = db.Column(db.Integer, db.ForeignKey("posts.id"))
    time = db.Column(db.String)

    def save_comment(self):
        db.session.add(self)
        db.session.commit()

class Subscriber(db.Model):
    __tablename__ = "subscribers"
    id = db.Column(db.Integer, primary_key = True)
    email = db.Column(db.String)

    def save_subscriber(self):
        db.session.add(self)
        db.session.commit()

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField
from wtforms.validators import Required

class PostForm(FlaskForm):

    title = StringField('Post title',validators=[Required()])
    content = TextAreaField('Post', validators=[Required()])
    submit = SubmitField('Submit')

class SubscribeForm(FlaskForm):
    email = StringField("Enter email", validators = [Required()])
    submit = SubmitField("Subscribe")

class AddComment(FlaskForm):
    name = StringField("Name", validators = [Required()])
    comment = TextAreaField("Comment", validators = [Required()])
    submit = SubmitField("Comment")

app/__init__.py
from flask import Flask
# from .config import DevConfig
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

bootstrap = Bootstrap()
db = SQLAlchemy()

def create_app(config_name):

    # Initializing application
    app = Flask(__name__)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')

    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)

    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,error

app/main/views.py
from flask import render_template,redirect,url_for,abort
from . import main
from .forms import PostForm,SubscribeForm,AddComment
from flask_login import login_required,current_user
from ..models import Post,User,Subscriber,Comment
from datetime import datetime
from .. import db
import requests
import json


# Views
@main.route('/',methods= ['POST', 'GET'])
# @login_required
def index():

    '''
    View root page function that returns the index page and its data
    '''
    form = SubscribeForm()
    if form.validate_on_submit():
        email = form.email.data
        new_subscriber = Subscriber(email = email)
        db.session.add(new_subscriber)
        db.session.commit()
        # flash("Thank You for subscribing!")
        return redirect(url_for("main.index"))
    post = Post.query.order_by(Post.time.desc())

    display=requests.get('http://quotes.stormconsultancy.co.uk/random.json').json()
    print(display)
    message='Hello variable block test'
    title = 'Note Book'
    return render_template("index.html",post = post,form = form,title = title,display=display)

@main.route("/add/post/",methods = ["GET","POST"])
@login_required
def add_post():
    form = PostForm()
    title = "Add an article"


    if form.validate_on_submit():
        title = form.title.data
        content = form.content.data
        posted = str(datetime.now())
        print(posted)
        # if "photo" in request.files:
        #     pic = photos.save(request.files["photo"])
        #     file_path = f"photos/{pic}"
        #     image = file_path
        new_post = Post(title = title, content = content, time = posted)
        new_post.save_post()
        # subscribers = Subscriber.query.all()
        # emails = []
        # for subscriber in subscribers:
        #     emails.append(subscriber.email)
        # for email in emails:
        #     create_mail("Update!","email/update",email, user = current_user)
        # print(emails)
        return redirect(url_for('main.index'))

    return render_template("posts.html",form = form,title = title)

@main.route("/profile/<id>")
def profile(id):
    user = User.query.filter_by(id = id).first()
    posts = Post.query.filter_by(user_id = user.id).order_by(Post.time.desc())
    title = user.username

    if user is None:
        abort(404)
    return render_template("profile/profile.html", user = user,posts = posts, title = title)

@main.route("/comments/<int:id>",methods = ["GET","POST"])
def add_comment(id):
    form = AddComment()
    if form.validate_on_submit():
        name = form.name.data
        content = form.comment.data
        new_comment = Comment(name = name, content = content)
        new_comment.save_comment()
        return redirect(url_for('main.index'))
    comments = Comment.query.all()

    return render_template("comments.html",form = form,comments = comments)

@main.route("/delete/comment/<id>")
def delete_comment(id):
    comment = Comment.query.all()
    db.session.delete(comment)
    db.session.commit()
    return redirect(url_for("main.comments"))

app/templates/base.html
{% extends 'bootstrap/base.html'%}

<!-- Navbar block  -->
{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}

app/templates/comments.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf%}

{% block content%}
<div class="row comment-row">
  <div class="comment-card col-sm-4">
    <h3>Leave a Comment</h3>
    {{wtf.quick_form(form)}}
  </div>
  <div class="comments-card col-sm-6">
    <h3>Comments</h3>
    <!-- <p>There are no comments</p> -->
    {% if comments %}
    {% for comment in comments%}
    <p><strong>{{comment.name}}</strong>: {{comment.content}} {% if current_user.is_authenticated %}<a href="{{url_for('main.delete_comment', id = comment.id)}}"><i class="fas fa-trash-alt"></i></a>{% endif %}</p>
    {% endfor%}
    {% else %}
    <p>There are no comments</p>
    {% endif %}
  </div>
</div>
{% endblock%}

app/templates/fourOwfour.html
 {% extends 'base.html'%}

{% block content %}
    <h1>WHOOOPS we can't find that page</h1>
{% endblock %}

app/templates/index.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf%}

{% block content%}
<div class="jumbotron">
  <div>
    <p> {{display.quote}} </p>
  </div>
  <div>
    <p> {{display.author}} </p>
  </div>

</div>


<div class="home">
  <!-- <h1 class="title text-center display-4">Articles</h1> -->
  <div class="row">
    <div class="posts col-sm-9">
      <div class="container px-auto">

        {% for post in posts %}
        <div class="post-card mb-5 text-center">
          <div class="img-container">
            <img class="text-center img-responsive" src="{{url_for('static', filename=post.image)}}" alt="" height="600px" width="750px">
          </div>
          <h2>{{post.title}}</h2>
          <div class="content">
            <p>{{post.content}}</p>
          </div>
          <div class="links">
            <a href="{{url_for('main.post_page',id = post.id)}}" class="btn btn-info">Read More</a>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>
<footer>
  <div class="col-sm-2" style="overflow-y: hidden; margin-top: 5px">
    {{wtf.quick_form(form)}}
  </div>
</footer>
{% endblock %}

app/templates/navbar.html
<div class="navbar navbar-inverse" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"> Note Book </a>
    </div>
    <!-- <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="/">Home</a></li>
            </div> -->
    <ul class="nav navbar-nav navbar-right">
      {% if current_user.is_authenticated %}
      <li><a href="{{url_for('main.add_comment', id = current_user.id)}}">Comment on quotes</a></li>
      <li><a href="{{url_for('main.add_post')}}">Add an Article</a></li>
      <li><a href="{{url_for('main.profile', id = current_user.id)}}">{{current_user.username}}</a></li>
      <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
      {% else %}
      <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
      {%endif%}
    </ul>
  </div>
</div>

app/templates/posts.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}


{% block content%}
    <div class="container">
        <form class="form-group" method="post" enctype="multipart/form-data">
            {{form.hidden_tag()}}
            {{form.title.label}}
            {{form.title(class = "form-control",style="margin-bottom: 10px;")}}
            {{form.content.label}}
            {{form.content(class = "form-control", style="margin-bottom: 15px;")}}
            <!-- <input type="file" name="photo" id="" class="form-control" style="margin-bottom:15px" required> -->
            {{form.submit(class = "btn btn-sm btn-info")}}
        </form>
    </div>
{% endblock%}

app/templates/profile/profile.html
{% extends "base.html" %}

{% block styles%}
    {{super()}}
    <link rel="stylesheet" href="../static/css/styles.css">
{% endblock %}

{% block content %}
<div class="container">
    <h1>{{current_user.name | upper}}</h1>
    <div class="row">
        <div class="col-sm-12 col-md-5 col-lg-5">
            {% if user.image %}
            <div class="img-container">
                <img src="{{url_for('static', filename = user.image)}}" class="img-thumbnail profile-pic">
            </div>
            {% else %}
            <p>{{user.username}} has not uploaded an image or written any article</p>
            {% endif %}
        </div>
    </div>
    <hr>
    <div class="">
        <h3 class="text-center">My Articles</h3>
        <div class="my-posts">
            {% if posts %}
            {% for post in posts %}
            <div class="post-card mb-5 text-center">
                <div class="img-container">
                    <img class="text-center img-responsive" src="{{url_for('static', filename=post.image)}}" alt="" height="600px"
                        width="750px">
                </div>
                <h2>{{post.title}}</h2>
                <h3><em>By {{post.user.username}}</em></h3>
                <div class="content">
                    <p>{{post.content[0:200] + "..."}}</p>
                </div>
                <div class="links">
                    <a href="{{url_for('main.post_page',id = post.id)}}" class="btn btn-info">Read More</a>
                    {% if current_user.is_authenticated%}
                    <a href="{{url_for('main.delete',id=post.id)}}" class="btn btn-danger">Delete</a>
                    {% endif %}
                </div>
            </div>
            {% endfor %}
            {% else %}
            <h2>You have no articles yet</h2>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}